In [1]:
import numpy as np
c= np.array([[1,3],[2,1]])
print(c)
c=np.linalg.det(c)
c=round(c)
print(c)

[[1 3]
 [2 1]]
-5


In [ ]:
import numpy as np
a= np.array([[1,-1],[-2,3]])
print(a)
a=np.linalg.det(a)
a=round(a)
print(a)
# c=np.pick.row(1)
# print(c)

[[ 1 -1]
 [-2  3]]
1


 $A^{-1}$ = adj/det A

pick row z= zij*cij+zij*cij...zin*cin

Rumus=1/det matriks*transpose


det z21= $\begin{split}
\begin{equation}
\left[ \begin{array}{rrrr}   3&3&4&2\\
    3& 4& 1&3\\
    3& 4 & 1&2\\
    3&4&5&2 \end{array}\right]
\end{equation}
\end{split}$= 12

det z22=$\begin{split}
\begin{equation}
\left[ \begin{array}{rrrr}   2&3&4&2\\
    1& 4& 1&3\\
    2& 4 & 1&2\\
    2&4&5&2 \end{array}\right]
\end{equation}
\end{split}$= 16

det z23=$\begin{split}
\begin{equation}
\left[ \begin{array}{rrrr}   2&3&4&2\\
    1& 3& 1&3\\
    2& 3 & 1&2\\
    2&3&5&2 \end{array}\right]
\end{equation}
\end{split}$= 0

det z24=$\begin{split}
\begin{equation}
\left[ \begin{array}{rrrr}   2&3&3&2\\
    1& 3& 4&3\\
    2& 3 & 4&2\\
    2&3&4&2 \end{array}\right]
\end{equation}
\end{split}$= 0

det z25=$\begin{split}
\begin{equation}
\left[ \begin{array}{rrrr}   2&3&3&4\\
    1& 3& 4&1\\
    2& 3 & 4&1\\
    2&3&4&5 \end{array}\right]
\end{equation}
\end{split}$= 12

Menghitung determinan matriks dan invers matriks menghitung invers matriks 5x5

rumus  $z^{-1}$ = 1/det matriks.$z^{T}$

z= $\begin{split}
\begin{equation}
\left[ \begin{array}{rrrr}   2&3&3&4&2\\
    2& 3& 4&1&3\\
    1& 3 & 4&1&3\\
    2&3&4&1&2\\
    2&3&4&5&2 \end{array}\right]
\end{equation}
\end{split}$

In [10]:
l= np.array([[2,3,3,4],[1,3,4,1],[2,3,4,1],[2,3,4,5]])
print(l)
l=np.linalg.det(l)
print(f'Determinannya:',{l})
l=round(l)
print(l)

[[2 3 3 4]
 [1 3 4 1]
 [2 3 4 1]
 [2 3 4 5]]
Determinannya: {11.999999999999995}
12
