
- Sifat-sifat Determinan
- Mancari fungsi dipython menghitung determinan identitas
- matriks Identitas 2x2 dan 3x3 dan cari determinannya

2.merubah baris merubah tanda determinan

In [28]:
import numpy as np
A= np.array([[2,3],[4,3]])
print(A)
A=np.linalg.det(A)
print(f'Determinannya:',{A})

[[2 3]
 [4 3]]
Determinannya: {-6.0}


In [2]:
import numpy as np
c= np.array([[1,2,1],[3,1,2],[2,1,2]])
print(c)
c=np.linalg.det(c)
print(f'Determinannya:',{c})

[[1 2 1]
 [3 1 2]
 [2 1 2]]


In [25]:
import numpy as np
e= np.array([[1,2,1],[2,4,2],[2,1,2]])
print(e)
#Determinan
e=np.linalg.det(e)
print(f'Determinannya:',{e})

[[1 2 1]
 [2 4 2]
 [2 1 2]]
0.0


In [27]:
import numpy as np
g= np.array([[6,2,4],[2,4,2],[4,2,4]])
print(g)
g=np.linalg.det(g)
print(f'Determinannya:',{g})

[[6 2 4]
 [2 4 2]
 [4 2 4]]
Determinannya: {24.000000000000014}


In [8]:
import numpy as np
h= np.array([[6,8],[4,2]])
print(h)
h=np.linalg.det(h)
print(f'Determinannya:',{h})


[[6 8]
 [4 2]]
-19.999999999999996


- ketika ada Matriks A dan B dengan ordo yang sama, matriks B Merupakan kelipatan dari matriks A dan determinan dari matriks A sudah diketahui maka determinan B = Kelipatan dari elemen matriks dikali hasil determinan matriks A.
contoh: $2^{3}$.3

In [26]:
import numpy as np
D= np.array([[3,1,2],[1,2,1],[2,1,2]])
g= np.array([[6,2,4],[2,4,2],[4,2,4]])
print(D)
D=np.linalg.det(D)
print(f'Determinannya:',{D})
print()
print(g)
g=np.linalg.det(g)
print(f'Determinannya:',{g})

[[3 1 2]
 [1 2 1]
 [2 1 2]]
Determinannya: {3.000000000000001}

[[6 2 4]
 [2 4 2]
 [4 2 4]]
Determinannya: {24.000000000000014}


A=$\begin{split}
\begin{equation}
\left[ \begin{array}{rrrr}   3 &4\\
    2 & 1 \end{array}\right]
\end{equation}
\end{split}$

A2=$\begin{split}
\begin{equation}
\left[ \begin{array}{rrrr}   7 &5\\
    2 & 1 \end{array}\right]
\end{equation}
\end{split}$

A2=$\begin{split}
\begin{equation}
\left[ \begin{array}{rrrr}   4 &1\\
    2 & 1 \end{array}\right]
\end{equation}
\end{split}$

In [13]:
import numpy as np
a= np.array([[4,1],[2,1]])
print(a)
a=np.linalg.det(a)
print(f'Determinannya:',{a})

[[4 1]
 [2 1]]
Determinannya: {2.0}


In [15]:
#Mtriks Segitiga atas
import numpy as np
k= np.array([[4,1,3],[0,2,1],[0,0,1]])
print(k)
k=np.linalg.det(k)
print(f'Determinannya:',{k})

[[4 1 3]
 [0 2 1]
 [0 0 1]]
Determinannya: {7.999999999999998}


In [20]:
l= np.array([[1,0,0],[2,1,0],[4,1,3]])
print(l)
l=np.linalg.det(l)
print(f'Determinannya:',{l})

[[1 0 0]
 [2 1 0]
 [4 1 3]]
Determinannya: {2.9999999999999996}


Determinan matriks C= det(AB)

In [23]:
import numpy as np
a= np.array([[2,1],[1,1]])
print(a)
a=np.linalg.det(a)
print(f'Determinannya:',{a})
print()
b= np.array([[1,1],[1,1]])
print(b)
b=np.linalg.det(b)
print(f'Determinannya:',{b})

[[2 1]
 [1 1]]
Determinannya: {1.0}

[[1 1]
 [1 1]]
Determinannya: {0.0}


In [24]:
C=np.array([[3,3],[2,2]])
print(C)
C=np.linalg.det(C)
print(f'Determinannya:',{C})


[[3 3]
 [2 2]]
Determinannya: {0.0}
